### ISSUE TITLE
sys nicht gefunden in Fehlermeldung zu fehlenden Stored Procs

### ISSUE THREAD

**Issue by frickler24** [frickler24/RechteDB#88]
NameError: name 'sys' is not defined
[17/Feb/2019 19:07:46] "GET /rapp/ HTTP/1.1" 500 125789
Not Found: /favicon.ico
[17/Feb/2019 19:07:47] "GET /favicon.ico HTTP/1.1" 404 2400
Not Found: /favicon.ico
[17/Feb/2019 19:07:49] "GET /favicon.ico HTTP/1.1" 404 2400
[17/Feb/2019 19:07:52] "GET /rapp/stored_procedures/ HTTP/1.1" 200 6334
[17/Feb/2019 19:07:59] "GET / HTTP/1.1" 302 0
[17/Feb/2019 19:07:59] "GET /rapp HTTP/1.1" 301 0
Internal Server Error: /rapp/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 60, in callproc
    return self.cursor.callproc(procname)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 298, in callproc
    self._query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 304, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 217, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1305, 'PROCEDURE RechteDB.erzeuge_af_liste does not exist')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/RechteDB/RechteDB/rapp/views.py", line 116, in home
    cursor.callproc("erzeuge_af_liste")  # diese SProc benötigt die Orga nicht als Parameter
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in callproc
    return self.cursor.callproc(procname, params, kparams)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 60, in callproc
    return self.cursor.callproc(procname)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 298, in callproc
    self._query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 304, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 217, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1305, 'PROCEDURE RechteDB.erzeuge_af_liste does not exist')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/RechteDB/RechteDB/rapp/views.py", line 118, in home
    e = sys.exc_info()[0]
NameError: name 'sys' is not defined

Das ist passiert, nachdem alle SPs gelöscht wurden.

**Comment by frickler24** [comment]
Wird mit PR für #75 mit behoben

**Comment by frickler24** [comment]
Es gibt wieder Fälle: Leicht zu reproduzieren, indem einfach mal alle Stored Procs entfernt werden.
![grafik](https://user-images.githubusercontent.com/6292952/55827885-896e8400-5b0b-11e9-9e5d-2a9a20f754dc.png)
